# Generated by Django 3.2.9 on 2021-12-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
