# Generated by Django 3.2.9 on 2021-12-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
